### ISSUE TITLE
Issues in opening a triage

### ISSUE THREAD

**Issue by xycloops123** [biggiesmallsAG/nightHawkResponse#12] opened 2016-08-15 17:55 UTC
Hello NightHawk Team,

After uploading the .mans file I am unable to open it?
Any solutions for this?
Thanks
XM

**Comment by biggiesmallsAG** [comment] 2016-08-15 23:04
Hi XM, 

Can you give me some more details;

- Is this a mans file from Redline or HX?
- Did you name the case the same as the endpoint name?
- Does the case appear with the endpoint inside it on the root tree the left?
- Did you use our audit script to take build the collection?

Regards,

Dan

**Comment by xycloops123** [comment] 2016-08-16 18:16
Hi Dan,

I performed first 3 steps and have missed the 4th one
1. I am using a file from HX
2. Uploaded the file using the hostname that comesup in the HX console
3. Yes it does appear on the root tree 
![capture](https://cloud.githubusercontent.com/assets/7406483/17710603/cfd44762-63a2-11e6-848a-db39b07bcce6.JPG)

4.Did you use our audit script to take build the collection?
Can you please elaborate more on this changes in the script and deploying it?

Regards,
XM

**Comment by xycloops123** [comment] 2016-08-16 19:51
Hi Dan, 

https://github.com/biggiesmallsAG/nightHawkResponse/issues/6

The above issue cleared the first step of opening a triage but now as I am able to look at the root tree, the visuals are not visible on the right hand side. 

Please Advise
Thanks
XM
![capture](https://cloud.githubusercontent.com/assets/7406483/17713505/23ba1d36-63b0-11e6-8863-51603e6e26fd.JPG)

**Comment by biggiesmallsAG** [comment] 2016-08-16 23:04
Hi XM,

Did you change the IP address of the VM using the supplied "/opt/nighthawk/bin/nighthawkctl set-ip <new_ipaddress> " ? It seems that your issue is likely due to change the IP address without using the nighthawkctl script. Can you confirm?

Regards,

Daniel

**Comment by xycloops123** [comment] 2016-08-16 23:15
Hi Dan,

Yes I did change the IP using the nighthawkctl script.

Thanks
XM

**Comment by biggiesmallsAG** [comment] 2016-08-16 23:50
Hi XM,

Can you open the developer console and screenshot me the network response that you get when you click on an audit type? Also, can you zip up the logs in /opt/nighthawk/var/logs and send them over so i can see.

Regards,

Dan

**Comment by xycloops123** [comment] 2016-08-17 00:20
Hi Dan,
![capture](https://cloud.githubusercontent.com/assets/7406483/17720304/a77f0b7a-63d5-11e6-9be5-13ebf3f01816.JPG)

**Comment by biggiesmallsAG** [comment] 2016-08-17 00:32
Hi XM,

Nope those map files are not needed. Can you get me the log files ?

Regards,

Dan

**Comment by xycloops123** [comment] 2016-08-22 23:45
Experiencing some issues in uploading the log files.

**Comment by biggiesmallsAG** [comment] 2016-08-23 00:14
Hey mate, 

send them to my email; daniel.eden@gmail.com

Regards,

Dan

**Comment by nabeelz6** [comment] 2016-09-07 20:11
I'm seeing this exact issue when trying clicking on any audit in the left-hand tree (using HX mans package). Page just hangs...

I'm using latest iso and didn't change the IP address. There seems to be loop for the same errors in console log (Failed to parse SourceMap: https://192.168.42.173/______.js.map, etc)

**Comment by nabeelz6** [comment] 2016-09-14 15:22
Any word on this!?

**Comment by biggiesmallsAG** [comment] 2016-09-23 23:01
Hi Nabeel,

No issues with the websocket.log, the worker spawning/kill's are associated with connections made to the websocket loop. If a new request is made to the websocket endpoint and UWSGI is already serving sockets it will automatically spawn up new handlers to deal with the load.

Nabeel, what VM architecture are you using? VMware/Vbox/Parallels? Also, can you drop me all the logs in /opt/nighthawk/var/log directory. Zip them and send them to my email or review.

Also are you trying version 1.0.3? 

Regards,

Daniel.

**Comment by nabeelz6** [comment] 2016-10-03 14:02
Hi Daniel,

I'm using version 1.0.3 on VMware. Sure, I can email you the zip of the logs soon. Thanks!

**Comment by kaktis** [comment] 2017-06-14 19:22
Daniel,
I am also having issues with this exact issue where it freezes until the web page breaks and the logs start outputting logs about attempts to write to broken pipes. Was there a fix action associated with this issue? Thank you in advance for your time.

**Comment by biggiesmallsAG** [comment] 2017-06-17 07:49
Kaktis,

Are you on v1.0.3? The problem im pretty sure was to do with a regex that wasnt capturing the endpoint name from the url header correctly. I managed to reproduce this in v1.0.3 and pushed a fix up. 

If you remote into the VM, can you paste me what the urls.py looks like from the nighthawk django directory.

Dan

**Closed** 2018-02-08 11:02 UTC
